<a href="https://colab.research.google.com/github/keshavisha/Job_placement/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
     

In [9]:
df = pd.read_csv("/content/Placement_Data_Full_Class.csv")
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [10]:
df['status'].unique()

array(['Placed', 'Not Placed'], dtype=object)

In [11]:
df['specialisation'].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [12]:
df['ssc_b'].unique()


array(['Others', 'Central'], dtype=object)

In [13]:
df['gender'].unique()

array(['M', 'F'], dtype=object)

In [14]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'status'.
df['status']= label_encoder.fit_transform(df['status'])
df['status'].unique()


array([1, 0])

In [15]:
df['gender']= label_encoder.fit_transform(df['gender'])
df['gender'].unique()

array([1, 0])

In [16]:
df['ssc_b']= label_encoder.fit_transform(df['ssc_b'])
df['ssc_b'].unique()

array([1, 0])

In [17]:
df['specialisation']= label_encoder.fit_transform(df['specialisation'])
df['specialisation'].unique()

array([1, 0])

In [18]:
df['hsc_b']= label_encoder.fit_transform(df['hsc_b'])
df['hsc_b'].unique()

array([1, 0])

In [20]:
df['hsc_s']= label_encoder.fit_transform(df['hsc_s'])
df['hsc_s'].unique()

array([1, 2, 0])

In [21]:
df['degree_t']= label_encoder.fit_transform(df['degree_t'])
df['degree_t'].unique()

array([2, 0, 1])

In [22]:
df['workex']= label_encoder.fit_transform(df['workex'])
df['workex'].unique()

array([0, 1])

In [23]:
#distribute the dataset into two components X and Y
X = df.iloc[: , 0:13].values  
Y = df.iloc[: , 13].values  

In [33]:
#split the dataset into the training set and testing set.
from sklearn.model_selection import train_test_split as tts  
X_train, X_test, Y_train, Y_test = tts(X, Y, test_size = 0.4, random_state = 0)  

In [34]:
from sklearn.preprocessing import StandardScaler as SS  
SC = SS()  
   
X_train = SC.fit_transform(X_train)  
X_test = SC.transform(X_test)  

In [35]:
from sklearn.decomposition import PCA
 
pca = PCA(n_components = 6)
 
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
 
explained_variance = pca.explained_variance_ratio_